### ISSUE TITLE
MATLAB.jl: Print Output during evaluation in MATLAB

### ISSUE THREAD

**Issue by GravityAssisted** [JuliaLang/MATLAB.jl#30]
Hi,

I have a certain function in matlab say: `Star(filename)`
when I run `Star' via Matlab it prints code progress as it runs. It takes a while to run and hence it prints some progress to the Maltab prompt after fixed time intervals.

Now when I run the following code in Julia REPL

<pre><code>using MATLAB;
S = MSession();
eval_string(s,"Star('test')");
</code></pre>

It still runs just fine but it doesn't print anything until <b>after</b> the Matlab function is finished. Is there someway to change this behavior of `MATLAB.jl` and have Julia print Matlab prompt output as and when it appears ?

thanks a lot !

**Comment by simonster** [comment]
As far as I know, the [MATLAB Engine API](http://www.mathworks.com/help/matlab/calling-matlab-engine-from-c-c-and-fortran-programs.html) only supports returning a string with the output when the function is finished. It might be possible to redirect stdout using a MEX file, but I'm not sure whether that's something we want to do here.

**Comment by GravityAssisted** [comment]
Interesting, thanks for the info. I temporarily solved the problem by writing the Matlab output to a log file and using the unix  `tail`  command inside Julia (via `;`) to query that file for output.

`tail -f outputlog_file`

A more elegant and portable solution can be accomplished using Julia threads but this is good enough for now.

Will close this.
