### ISSUE TITLE
Hide MATLAB Engine Session Window on Windows

### ISSUE THREAD

**Issue by jeremy-y12** [JuliaLang/MATLAB.jl#31]
Please allow hiding the MATLAB Command Window on Windows. This can be done by using the [engSetVisible](http://www.mathworks.com/help/matlab/apiref/engsetvisible.html) function.

I would argue that the default should be to not show this window, as I expect the interaction to be done only from within Julia. A use case would be to plot something using MATLAB, which does not require the command window. I also believe that OSX and Linux also do not show this window by default.

**Comment by jeremy-y12** [comment]
The followings lines simply need to be added to `engine.jl` after the engine creation:

		if OS_NAME == :Windows
		    vis = ccall(engfunc(:engSetVisible ), Cint, (Ptr{Void}, Cint), ep, 0)
		end
Note that this makes the window open and close in the background. I do not think there is a way around this...

**Comment by timholy** [comment]
You can edit the source file on GitHub and it will submit a "pull request". There are also instructions on GitHub and [here](http://docs.julialang.org/en/release-0.3/manual/packages/#package-development) about how to submit more complex contributions.

**Comment by jeremy-y12** [comment]
Thanks Tim, I submitted a pull request here #33.

**Comment by simonster** [comment]
Fixed by #33
