### ISSUE TITLE
Is it possible to support MATLAB gpuArray?

### ISSUE THREAD

**Issue by AStupidBear** [JuliaLang/MATLAB.jl#42]
Since Julia now dosen't have high level supports for GPU computing, MATLAB's GPU operation is attrative. I don't know if it would be difficult to implement such things:
```julia
gA=gpuArray(A)
gB=sin(gA)
```
while gpuArray will call into MATLAB to create a gpuArray and returns a pointer, sin will use MATLAB builtin GPU sin function and returns a pointer.

**Comment by simonster** [comment]
As far as I know, no one is interested in implementing this through MATLAB, but you might be interested in https://github.com/JuliaComputing/ArrayFire.jl

**Comment by AStupidBear** [comment]
Thank you for your suggestions.
